alter table books_for drop FOREIGN KEY fk_tic_eve_usr;
alter table books_for drop FOREIGN KEY fk_tic_eve_eve;
alter table transactions drop FOREIGN KEY fk_tran_bank;
alter table transactions drop FOREIGN KEY fk_tran_usr;
alter table ticket drop FOREIGN KEY fk_trans;
alter table ticket drop FOREIGN KEY fk_tick_event;
alter table event drop FOREIGN KEY fk_event;
alter table account drop FOREIGN KEY fk_admin_acc;
alter table account_admin drop FOREIGN KEY fk_admin;
alter table account_user drop FOREIGN KEY fk_user;
alter table account_event_manager drop FOREIGN KEY fk_event_manager;
drop table books_for;
drop table ticket;
drop table event;
drop table transactions;
drop table bank;
drop table account_admin;
drop table account_event_manager;
drop table account_user;
drop table account;
